### ISSUE TITLE
Will this library support multi search?

### ISSUE THREAD

**Issue by peterbedor** [swiftype/swiftype-app-search-javascript#44]
I couldn't find a roadmap anywhere so I wanted to ask if you all plan to support [multi search](https://swiftype.com/documentation/app-search/api/search#multi) any time in the future?

Sorry if I've overlooked anything if the ability exists.

Thanks!

**Comment by JasonStoltz** [comment]
Hey @peterbedor. Yes, definitely. I'm actually hoping to push out a new version next week which would include multi search.

**Comment by peterbedor** [comment]
@JasonStoltz Awesome!  Thanks for the update.
